### ISSUE TITLE
Seeking Assistance with Connecting GYML8511 Sensor to Arduino

### ISSUE THREAD

**Issue by Olvera-Orozco-Miguel-Angel** [RobTillaart/ML8511#10] opened 2024-04-02 03:53 UTC
Hello everyone,

I hope you're doing well. I'm currently working on connecting a sensor to my Arduino project and could use some guidance.

I've been following the connection instructions from this page [  link](https://learn.sparkfun.com/tutorials/ml8511-uv-sensor-hookup-guide/all) ], but I'm encountering some uncertainty. Given the unique nature of my sensor (GYML8511), I'm unsure if the connection might differ from the instructions provided.

Could someone kindly assist me with understanding how to properly connect the GYML8511 sensor to Arduino?

Any help or insights would be greatly appreciated. Thank you very much in advance for your assistance.

Best regards,

**Comment by RobTillaart** [comment] 2024-04-02 07:00
Thanks for your question
I will look into it later this week. Have some other tasks with prio. 
Did you read the datasheet?
Do you have a link to the datasheet.?

**Comment by RobTillaart** [comment] 2024-04-02 11:23
> I'm currently working on connecting a sensor to my Arduino project and could use some guidance.

OK, please note that the Arduino Forum is a better place to discuss project guidance. 
This is a place to discuss the working (or not) of this library.

> Could someone kindly assist me with understanding how to properly connect the GYML8511 sensor to Arduino?

Looked at the link of the sensor - https://learn.sparkfun.com/tutorials/ml8511-uv-sensor-hookup-guide/all - you provided and I have little to add to their code. OK, they do not use my library however it should work,

See also - http://wiki.sunfounder.cc/index.php?title=GYML8511_UV_Sensor - roughly identical 

> ... but I'm encountering some uncertainty.

So what is the problem?

PLease note that UV sensors do not work in house (unless you use a UV emitting light)

**Comment by RobTillaart** [comment] 2024-04-11 08:14
@Olvera-Orozco-Miguel-Angel 
As there is no answer for a week I assume the problem is solved, so I close the issue.

**Closed as completed by RobTillaart** 2024-04-11 08:14 UTC
Labels: question
